# Generated by Django 4.2.2 on 2023-06-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='episodes',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Кол-во сезонов, серий, фильмов'),
        ),
    ]
