# Generated by Django 4.2.2 on 2023-06-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_episodes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='genre',
            new_name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='genres',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Жанры'),
        ),
    ]
