# Generated by Django 4.2.3 on 2023-07-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_created_at_article_updated_at_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
